name: simple
description: 'ODSC'

# schedule: weekly
pipeline:

  init:
    method: seed
    params:
      urls:
        - https://opendataservices.coop
    handle:
      pass: fetch

  fetch:
    # Download the seed page
    method: fetch
    handle:
      pass: parse

  parse:
    method: parse
    params:
      store:
        or:
          - mime_group: archives
          - mime_group: documents
    handle:
      store: store
      fetch: fetch
  
  store:
    method: directory
    params:
      path: /data/results